/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package app.dto {

[Bindable]
[RemoteClass(alias="app.dto.Customer")]
    public class Customer extends CustomerBase {
public function Customer(){
    super();
  }

}
}