/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package app.dto {
	import mx.collections.ArrayCollection;
	import mx.collections.ArrayList;
	import mx.collections.ListCollectionView;

[Bindable]
[RemoteClass(alias="app.dto.Login")]
    public class Login extends LoginBase {
	public function Login(){
	    super();
		this.username = "";
		this.password = "";
		this.roles = new ArrayCollection();
	  }
	}
}